# Generated by Django 3.1.4 on 2020-12-06 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.PositiveIntegerField()),
                ('content', models.CharField(max_length=280)),
                ('time_stamp', models.DateTimeField()),
                ('likes_counter', models.PositiveIntegerField()),
            ],
        ),
    ]
