# Generated by Django 3.1.4 on 2020-12-06 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='likes_counter',
            field=models.PositiveIntegerField(default='0'),
        ),
    ]
