# Generated by Django 3.1.4 on 2020-12-11 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_follow'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='number_of_followed',
            field=models.PositiveIntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='user',
            name='number_of_followers',
            field=models.PositiveIntegerField(default='0'),
        ),
    ]
